osx_image: xcode8.3

dist: trusty
sudo: true

language: node_js
node_js: "lts/*"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_script:
  - brew install rpm
  - npm update @suen/music-api
  - npm update @suen/electron-updater
  - wget http://collection.b0.upaiyun.com/softwares/upx/upx-darwin-amd64-v0.2.3 -O upx
  - chmod 755 upx

script:
  - MUSICLAKEURL=$MUSICLAKE_URL npm run build-file
  - ./upx --auth $UPX_AUTH sync -delete --strong ./dist/electron/
  - npm run build:publish

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email: false